spring.application.name=backend
server.port=9090

# Database connection
spring.datasource.url=jdbc:h2:mem:campusnexus_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate / JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# File upload settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Upload folder
app.upload.dir=uploads/resources

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=836518443998-mj8q45nl63rtg4ah68q6csblvhbfc0gj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Frontend URL
app.frontend.url=http://localhost:5173

# Admin emails - these Google accounts become ADMIN
app.admin.emails=campusnexus29@gmail.com