spring.application.name=backend
server.port=9090

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/campusnexus_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo
spring.datasource.username=campususer
spring.datasource.password=StrongPassword123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File upload settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Resource upload folder
app.upload.dir=uploads/resources

# Ticket upload folder
app.ticket.upload.dir=uploads/tickets

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=836518443998-mj8q45nl63rtg4ah68q6csblvhbfc0gj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Frontend URL
app.frontend.url=http://localhost:5173

# Admin emails
app.admin.emails=campusnexus29@gmail.com

# Staff emails 
app.staff.emails=binithisliit@gmail.com,banukasliit@gmail.com